openapi: "3.0.0"
info:
  title: "UniAPI"
  version: "0.0.1"
paths:
  /:
    get:
      description: Root GET
      x-openapi-router-controller: api.get
      operationId: rootGet
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/uniResponse'
        "500":
          description: Internal Server Error
      summary: Root GET

  /uniPostJson: ####### ======= uniPostJson ======= #######
    post:
      description: Unified entrance to the API (Json)
      x-openapi-router-controller: api.unipost
      operationId: uniPostJson
      parameters:
        - description: operator login token
          explode: false
          in: header
          name: token
          required: false
          schema: ####### Header Schema for uniPostJson #######
            oneOf:
              - type: string
              - type: object
          style: simple
      requestBody:
        content:
          application/json:
            schema: ####### Request Body Schema for uniPostJson #######
              type: object
              title: Unified Request Body (Json)
              description: Request body for the unified API entrance
              properties:
                op:
                  type: string
                  title: Operation Code
                  description: The operation code
                data:
                  oneOf:
                    - type: object
                    - type: array
                    - type: string
                    - type: number
                    - type: integer
                    - type: boolean
                  title: Operation Payload
                  description: The data payload for the operation
              required:
                - op
                - data
            encoding:
              op:
                contentType: text/plain
              data:
                contentType: application/json
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/uniResponse'
            application/octet-stream:
              schema:
                type: string
                format: binary
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: An unified entrance to the API (Json)
      tags:
        - uniPostJson
    options:
      description: CORS preflight handler
      x-openapi-router-controller: api.unipost
      operationId: uniPostOptions
      responses:
        "200":
          description: OK
      summary: CORS preflight handler

  /uniPostMultipart: ####### ======= uniPostMultipart ======= #######
    post:
      description: Unified entrance to the API (Multipart)
      x-openapi-router-controller: api.unipost
      operationId: uniPostMultipart
      parameters:
        - description: operator login token
          explode: false
          in: header
          name: token
          required: false
          schema: ####### Header Schema for uniPostMultipart #######
            oneOf:
              - type: string
              - type: object
          style: simple
      requestBody:
        content:
          multipart/form-data:
            schema: ####### Request Body Schema for uniPostMultipart #######
              type: object
              title: Unified Request Body
              description: Request body for the unified API entrance
              properties:
                op:
                  type: string
                  title: Operation Code
                  description: The operation code
                data:
                  type: object
                  properties: {} # prevent key error
                  additionalProperties: true # allow arbitrary keys
                  title: Operation Payload object
                  description: The data payload for the operation
                file:
                  type: string
                  title: File
                  description: The file to be uploaded (if any)
                  format: binary
                files:
                  type: array
                  title: Files
                  description: The files to be uploaded (if any)
                  items:
                    type: string
                    format: binary
              required:
                - op
                - data
            encoding:
              op:
                contentType: text/plain
              data:
                contentType: application/json
              file:
                contentType: application/octet-stream
              files:
                contentType: application/octet-stream
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/uniResponse'
            application/octet-stream:
              schema:
                type: string
                format: binary
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: An unified entrance to the API (Multipart)
      tags:
        - uniPostMultipart
    options:
      description: CORS preflight handler
      x-openapi-router-controller: api.unipost
      operationId: uniPostOptions
      responses:
        "200":
          description: OK
      summary: CORS preflight handler

components:
  schemas:
    uniResponse:
      type: object
      title: Unified Response
      description: Generic response that can contain any data
      properties:
        data:
          oneOf:
            - type: object
            - type: array
            - type: string
            - type: number
            - type: integer
            - type: boolean
          title: Any Data
          description: The data response, could be anything
      required:
        - data